cargo-features = ["edition2021"]

[package]
name = "erlang_nif_binding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.53.1"
which = "4.2.4"
